# Generated by Django 5.2b1 on 2025-05-01 19:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=120)),
                ('Semester', models.CharField(max_length=120)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=120)),
                ('LastName', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=120)),
                ('Phone', models.CharField(max_length=120)),
                ('Role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Instructor', 'Instructor'), ('TA', 'Ta')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('SectionNum', models.CharField(max_length=120)),
                ('ScheduledDays', models.CharField(blank=True, choices=[('U', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')], help_text='Comma-separated list of scheduled days (e.g., M,T,W).', max_length=20)),
                ('ScheduledStartTime', models.TimeField(default=datetime.time(9, 0))),
                ('ScheduledEndTime', models.TimeField(default=datetime.time(10, 0))),
                ('SectionType', models.CharField(choices=[('Lab', 'Lab'), ('Lecture', 'Lecture')], max_length=20)),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScheduleAppData.courses')),
                ('Instructors', models.ManyToManyField(to='ScheduleAppData.user')),
            ],
        ),
    ]
