# Generated by Django 5.2 on 2025-04-21 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=120)),
                ('Semester', models.CharField(max_length=120)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=120)),
                ('LastName', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=120)),
                ('Phone', models.CharField(max_length=120)),
                ('Role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Instructor', 'Instructor'), ('TA', 'Ta')], max_length=20)),
                ('OfficeHours', models.CharField(blank=True, max_length=120, null=True)),
                ('OfficeLocation', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('AssignmentName', models.CharField(max_length=120)),
                ('DueDate', models.DateField()),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScheduleAppData.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('SectionNum', models.CharField(max_length=120)),
                ('Schedule', models.CharField(max_length=120)),
                ('SectionType', models.CharField(choices=[('Lab', 'Lab'), ('Lecture', 'Lecture')], max_length=20)),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScheduleAppData.courses')),
                ('InstructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScheduleAppData.user')),
            ],
        ),
        migrations.CreateModel(
            name='LabAssignment',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('SectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScheduleAppData.sections')),
                ('TAId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScheduleAppData.user')),
            ],
        ),
    ]
