# Generated by Django 5.2b1 on 2025-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleAppData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='HomeAddress',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='OfficeHours',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='OfficeLocation',
            field=models.CharField(default='', max_length=120),
        ),
    ]
