# Generated by Django 5.2b1 on 2025-05-04 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleAppData', '0002_user_homeaddress_user_officehours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='OfficeHours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='OfficeLocation',
        ),
        migrations.AddField(
            model_name='user',
            name='OfficeHourDays',
            field=models.CharField(blank=True, choices=[('U', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')], help_text='Comma-separated list of scheduled days (e.g., M,T,W).', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='OfficeHourEndTime',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='OfficeHourStartTime',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
